import "@/app/i18n-init";
import "./globals.css";

import { type Metadata } from "next";

import { Providers } from "@/app/providers";
import { getMessages, resolveLocale } from "@/shared/i18n/server";
import { getServerTheme } from "@/shared/theme/theme.server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = await resolveLocale();
  const initialTheme = await getServerTheme();
  const messages = await getMessages(locale);

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body>
        <Providers messages={messages} initialTheme={initialTheme}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
