import { headers } from "next/headers";
import "./globals.css";

export const runtime = "nodejs";

import { type Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import { Providers } from "@/app/providers";
import { ThemeScript } from "@/shared/theme/theme-script";
import { getServerTheme } from "@/shared/theme/theme.server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { readonly children: React.ReactNode }) {
  const headerStore = await headers();
  const nonce = headerStore.get("x-nonce");

  /**
   * ⚠️ Do not hard crash production on CSP failure
   */
  if (!nonce && process.env.NODE_ENV === "production") {
    console.error("Missing CSP nonce — middleware misconfiguration");
  }

  const safeNonce = nonce ?? null;

  const initialTheme = await getServerTheme();
  const locale = await getLocale();
  const messages = await getMessages();

  const brand = "default";

  return (
    <html
      suppressHydrationWarning
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      data-brand={brand}
      className={initialTheme === "dark" ? "dark" : undefined}
    >
      <body>
        <ThemeScript nonce={safeNonce} />

        {/* <ExternalScript src="https://www.google.com/recaptcha/api.js" nonce={safeNonce} /> */}
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers initialTheme={initialTheme}>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
