import "./globals.css";
import { type Metadata } from "next";
import { Suspense } from "react";

import { IntlDynamic } from "@/providers/dynamic/intl.dynamic";
import { NonceDynamic } from "@/providers/dynamic/nonce.dynamic";
import { ThemeDynamic } from "@/providers/dynamic/theme.dynamic";
import { StaticProviders } from "@/providers/static-root";

import { RootErrorBoundaryProvider } from "./root-error-boundary";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <RootErrorBoundaryProvider>
          <StaticProviders>
            <Suspense fallback={null}>
              <NonceDynamic />
              <IntlDynamic>
                <ThemeDynamic>{children}</ThemeDynamic>
              </IntlDynamic>
            </Suspense>
          </StaticProviders>
        </RootErrorBoundaryProvider>
      </body>
    </html>
  );
}
